version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: python -m tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  docs:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: docs
  py37-lint:
    <<: *common
    docker:
      - image: cimg/python:3.7
        environment:
          TOXENV: py37-lint
  py38-lint:
    <<: *common
    docker:
      - image: cimg/python:3.8
        environment:
          TOXENV: py38-lint
  py39-lint:
    <<: *common
    docker:
      - image: cimg/python:3.9
        environment:
          TOXENV: py39-lint
  py310-lint:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-lint
  py311-lint:
    <<: *common
    docker:
      - image: cimg/python:3.11
        environment:
          TOXENV: py311-lint
  py37-wheel:
    <<: *common
    docker:
      - image: cimg/python:3.7
        environment:
          TOXENV: py37-wheel
  py38-wheel:
    <<: *common
    docker:
      - image: cimg/python:3.8
        environment:
          TOXENV: py38-wheel
  py39-wheel:
    <<: *common
    docker:
      - image: cimg/python:3.9
        environment:
          TOXENV: py39-wheel
  py310-wheel:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-wheel
  py311-wheel:
    <<: *common
    docker:
      - image: cimg/python:3.11
        environment:
          TOXENV: py311-wheel
  py37-core:
    <<: *common
    docker:
      - image: cimg/python:3.7
        environment:
          TOXENV: py37-core
  py38-core:
    <<: *common
    docker:
      - image: cimg/python:3.8
        environment:
          TOXENV: py38-core
  py39-core:
    <<: *common
    docker:
      - image: cimg/python:3.9
        environment:
          TOXENV: py39-core
  py310-core:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-core
  py311-core:
    <<: *common
    docker:
      - image: cimg/python:3.11
        environment:
          TOXENV: py311-core
workflows:
  version: 2
  test:
    jobs:
      - docs
      - py37-lint
      - py38-lint
      - py39-lint
      - py310-lint
      - py311-lint
      - py37-wheel
      - py38-wheel
      - py39-wheel
      - py310-wheel
      - py311-wheel
      - py37-core
      - py38-core
      - py39-core
      - py310-core
      - py311-core
